server:
  port: 8080

spring:
  application:
    name: AuthenticifyApplication

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/web-application

  mail:
    host: smtp.gmail.com
    port: 587
    username: zhenyabaraniuk@gmail.com
    password: xopl tpme lvsk khmm
    properties:
      mail:
        transport:
          protocol: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: smtp

  graphql:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      exposed-headers: "*"
      allowed-origins: "*"

auth:
  jwt:
    refreshToken:
      expirationTimeInMinutes: 1000
    accessToken:
      expirationTimeInMinutes: 30
