server:
  port: 8080

spring:
  application:
<<<<<<< HEAD
    name: AuthenticifyApplication

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/web-application
=======
    name: UserConnect
  config:
    location: file:/path/to/application-local.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERCONNECT_DATABASE_USERNAME}
    password: ${USERCONNECT_DATABASE_PASSWORD}
    url: ${USERCONNECT_DATABASE_URL}
>>>>>>> 0d32522 (Updated README.md)

  mail:
    host: smtp.gmail.com
    port: 587
<<<<<<< HEAD
    username: zhenyabaraniuk@gmail.com
    password: xopl tpme lvsk khmm
=======
    username: ${USERCONNECT_MAIL_USERNAME}
    password: ${USERCONNECT_MAIL_PASSWORD}
>>>>>>> 0d32522 (Updated README.md)
    properties:
      mail:
        transport:
          protocol: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: smtp

  graphql:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      exposed-headers: "*"
      allowed-origins: "*"

auth:
  jwt:
    refreshToken:
      expirationTimeInMinutes: 1000
    accessToken:
      expirationTimeInMinutes: 30
